language: python

sudo: required
dist: trusty

python:
    - 2.7
    #- 3.6

install: 
    - pip install -r requirements.txt

script:
    #- py.test -v --cov=nilsas --cov=apps --cov-report term-missing
    - py.test -v --cov=./ --cov-report term-missing

after_success:
    #- coveralls
