codecov:
  notify:
    require_ci_to_pass: yes
  token: c4184b7b-d768-4ac9-b9bb-c179175f4992

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no

